FROM node:latest

# Create app directory
WORKDIR /src

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install --silent --production


# If you are building your code for production
# RUN npm install --only=production

# CMD ["npm", "start"]
